"use client";

import { useState, useEffect } from "react";
import { useLanguage } from "../../lib/LanguageContext";
import SiteNav from "../../components/SiteNav";
import SiteFooter from "../../components/SiteFooter";
import MobileCTA from "../../components/MobileCTA";

const injectFonts = () => { if (typeof document==="undefined"||document.querySelector("#jr-fonts")) return; const l=document.createElement("link"); l.id="jr-fonts"; l.rel="stylesheet"; l.href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Source+Sans+3:wght@300;400;600&display=swap"; document.head.appendChild(l); };
const C = { bg:"#0B1628",navy:"#1B2A4A",navyMid:"#243556",navyLight:"#2C3E5A",navyFade:"#162033",gold:"#C8952E",goldLight:"#D4A843",goldPale:"rgba(200,149,46,0.12)",cream:"#F5F3EF",white:"#FFFFFF",offWhite:"#E8E4DC",muted:"#7A8FA8",charcoal:"#2D2D2D" };
const f = { h:"'Montserrat', sans-serif", b:"'Source Sans 3', sans-serif" };
const Tag = ({children}) => <div style={{display:"inline-block",padding:"6px 16px",background:C.goldPale,borderRadius:"4px",marginBottom:"12px"}}><span style={{fontFamily:f.h,fontSize:"12px",fontWeight:700,color:C.gold,letterSpacing:"3px"}}>{children}</span></div>;
const GoldBar = () => <div style={{width:"60px",height:"3px",background:`linear-gradient(90deg,${C.gold},${C.goldLight})`,borderRadius:"2px",margin:"16px auto"}} />;

const T = {
  en: {
    heroTag: "FAQ",
    heroH1a: "Frequently Asked",
    heroH1b: "Questions",
    heroP: "Everything homeowners ask us — answered honestly. Can't find your question? Call (844) 444-3114 and we'll answer it directly.",
    stillTitle: "STILL HAVE QUESTIONS?",
    stillP: "We'd rather answer your question directly than have you guess. Call or text us — we respond fast.",
    emailBtn: "EMAIL US",
    categories: [
      { name:"General", icon:"🏠", faqs:[
        {q:"What services does JR One offer?",a:"We specialize in seamless aluminum gutters (6\" and 7\"), copper gutters, gutter guards (aluminum, standard, micro mesh, and EZ mesh), soffit and fascia installation, siding, SAGIPER architectural cladding, gutter repair, Peak 301 roof rejuvenation, Govee smart light installation, drainage installation (French drains, catch basins, channel drains), and comprehensive maintenance plans. We're aluminum exterior specialists — that's all we do, and we do it right."},
        {q:"What areas do you serve?",a:"We serve 21 cities across Tampa Bay and Florida's west coast: Bradenton, Brandon, Clearwater, Dunedin, Lakeland, Land O' Lakes, Largo, Lutz, New Port Richey, Palm Harbor, Plant City, Riverview, Ruskin, Sarasota, Spring Hill, St. Petersburg, Sun City Center, Tampa, Tarpon Springs, Temple Terrace, and Wesley Chapel. If you're within an hour of Tampa, call us — we probably cover your area."},
        {q:"Do you use subcontractors?",a:"Never. Every person on your property is a trained, full-time JR One crew member. We run three in-house crews. This is how we maintain quality control and accountability on every job. Many of the complaints homeowners have about other contractors come from subcontracted work — we eliminated that problem entirely."},
        {q:"How long has JR One been in business?",a:"JR One Aluminum LLC was formed in 2006 by Christopher Rivera. The family roots in the Tampa Bay gutter trade go back to 1990, when Christopher's father Javier Rivera began installing gutters in Tampa after immigrating from Honduras. Over 30 years of family experience in the Tampa gutter industry across two generations. Many of the gutter and soffit companies operating in the Tampa market today trace their knowledge back to Javier — people who worked for him, worked with him, or learned alongside him."},
        {q:"Do you speak Spanish?",a:"Yes. JR One is a fully bilingual company — English and Spanish. We communicate in whichever language you're most comfortable with from the first call through final walkthrough. All our insurance documents and resources are available in both languages."},
        {q:"Do you offer free estimates?",a:"Yes. We provide free on-site assessments for all services. We'll inspect your home, discuss your needs, and provide a detailed, transparent estimate with no obligation and no pressure. You can also use our online Aerial Estimator tool to measure your roof from satellite imagery and get an instant price range before we even visit."},
        {q:"What makes JR One different from other contractors?",a:"Three things: (1) We only do aluminum exteriors — gutters, soffit, fascia, siding, guards, drainage. No roofing, no painting, no general contracting. This means our crews are specialists, not generalists. (2) All in-house crews — no subcontractors, ever. (3) Family-owned and family-operated, with over 30 years of experience in the Tampa Bay gutter industry across two generations. We've installed on some of the same homes twice."},
        {q:"What is the Gold Standard process?",a:"Every JR One project follows four steps: Assess (inspect your home and identify the real problem), Design (custom solution with transparent pricing), Install (our trained crew does the work — no shortcuts), and Protect (final walkthrough, documentation, and warranty). This process applies to every service, every home, no exceptions."},
        {q:"Are you licensed and insured?",a:"Yes. JR One Aluminum LLC is fully licensed and insured in the state of Florida. We carry general liability insurance and workers' compensation coverage. We're happy to provide proof of insurance to any homeowner or property manager who requests it."},
      ]},
      { name:"Gutters", icon:"💧", faqs:[
        {q:"What gutter sizes do you install?",a:"We install 6\" and 7\" seamless aluminum gutters. 6\" handles most residential applications with excellent water capacity. 7\" is our high-capacity option for larger roof areas, steeper pitches, and commercial buildings. We assess your roof and recommend the right size — we don't default to undersized gutters to save a few dollars."},
        {q:"How much do new gutters cost in Tampa?",a:"Seamless aluminum gutter installation in Tampa varies based on gutter size (6\" or 7\"), linear footage, accessibility, number of corners, downspout configuration, and stories. We provide detailed, line-item estimates so you see exactly what you're paying for. Use our Aerial Estimator at jronegutters.com/estimator for an instant ballpark range."},
        {q:"What are seamless gutters and why do they matter?",a:"Seamless gutters are custom-formed on-site from a single continuous piece of aluminum — no seams, no joints, no splice points along the run. Traditional sectional gutters have joints every 10 feet that eventually leak. Seamless gutters eliminate those failure points, which means fewer leaks, less maintenance, and a cleaner look on your home."},
        {q:"How long do seamless gutters last?",a:"With proper maintenance, quality seamless aluminum gutters last 20–30 years in Florida's climate. The aluminum itself doesn't rust or rot. What shortens gutter life is neglect — clogged downspouts, standing water, and debris buildup that causes corrosion. That's why we recommend maintenance plans and gutter guards."},
        {q:"How long does gutter installation take?",a:"Most residential gutter installations are completed in a single day. Homes with complex rooflines, multiple stories, or combined projects (gutters + soffit/fascia + guards) may take 2–3 days. We give you a timeline before we start and stick to it."},
        {q:"What downspout options do you offer?",a:"We install standard rectangular, smooth rectangular, round (two sizes), 4×5 commercial, box commercial downspouts, and decorative rain chains. Downspout size and placement are calculated based on your gutter size and roof square footage to ensure proper water handling — not just aesthetics."},
        {q:"Do you offer copper gutters?",a:"Yes. We install premium copper half-round and K-style gutter systems with matching copper downspouts, leader heads, and rain chains. Copper develops a natural patina over time and lasts 50+ years with zero maintenance. It's a lifetime investment for homeowners who want the best."},
        {q:"Why should I hire a gutter specialist instead of my roofer?",a:"Roofing companies typically subcontract gutter work to the lowest bidder. The result is often incorrect pitch, thin-gauge material, and poor corner work that leads to leaks within a few years. We specialize exclusively in aluminum systems — it's all we do. Every installation is performed by our trained in-house crew using commercial-grade materials."},
        {q:"My gutters are overflowing during heavy rain. What's wrong?",a:"Three common causes: (1) Gutters are clogged with debris — needs cleaning. (2) Gutters are undersized for your roof area — common when builders install undersized gutters on homes that need 6\" or 7\". (3) Gutters are improperly pitched — water pools instead of flowing to the downspouts. We diagnose the exact cause during a free inspection."},
        {q:"Do you handle gutter repair or only full replacement?",a:"Both. We repair sagging sections, fix leaking seams and corners, replace damaged downspouts, re-pitch gutters for proper drainage, and re-secure hangers. If repair makes sense, we'll tell you. If your system is beyond repair, we'll be honest about that too."},
      ]},
      { name:"Gutter Guards", icon:"🛡️", faqs:[
        {q:"Do gutter guards really work?",a:"Yes — guards are highly effective at keeping debris out of your gutters and preventing clogs in downspouts and drainage. They don't eliminate all maintenance, but they dramatically reduce cleaning frequency from 2–4 times per year down to once per year or less. The real value is preventing the damage that clogged gutters cause: foundation erosion, fascia rot, landscape damage, and pest problems."},
        {q:"What types of gutter guards do you install?",a:"We install four types: Aluminum guards (solid with water channels — best for heavy debris), Standard screen guards (cost-effective general protection), Micro Mesh guards (finest filtration — blocks pine needles, shingle grit, and small seeds), and EZ Mesh guards (easy-maintenance option with excellent airflow). We recommend the right type based on your tree coverage and debris type."},
        {q:"Do I still need to clean my gutters after guards are installed?",a:"Yes, but much less often. Guards keep debris from getting inside your gutters — that's where the real damage happens. Surface buildup on top of guards still needs occasional clearing, typically once a year. Compare that to cleaning unprotected gutters 2–4 times per year. We offer maintenance programs to handle this for you."},
        {q:"What's the best gutter guard for pine needles?",a:"Micro mesh guards are the most effective option for pine needles. Standard screen guards have openings large enough for needles to pass through and accumulate inside. Micro mesh blocks everything down to shingle grit while still allowing full water flow. If you have pine trees, oak trees, or palm fronds, micro mesh is what we recommend."},
        {q:"Can guards be installed on my existing gutters?",a:"Yes. We retrofit guards onto existing gutter systems — you don't need new gutters to get guard protection. We inspect your existing gutters first to make sure they're in good condition, properly pitched, and securely attached. If repairs are needed, we handle those before installing guards."},
        {q:"What's the difference between your guards and LeafFilter or other national brands?",a:"National companies like LeafFilter use high-pressure sales, charge premium prices (often 2–3x local rates), and subcontract installation to whoever's available. We're the local team — you deal directly with us, get honest pricing without franchise markup, and our own crew does both consultation and installation. No salespeople in your living room for two hours."},
        {q:"Will gutter guards void my gutter warranty?",a:"No. Our guard installations are designed to work with your existing gutter system without modifying or damaging the gutters themselves. If we installed your gutters, the workmanship warranty remains fully intact."},
        {q:"How long do gutter guards last?",a:"Aluminum and micro mesh guards last 15–20+ years. They're exposed to the same weather as your gutters but don't carry water weight or debris buildup, so they typically outlast the gutters themselves. We use commercial-grade materials — not the thin stuff you find at home improvement stores."},
      ]},
      { name:"Soffit & Fascia", icon:"🏗️", faqs:[
        {q:"What's the difference between soffit and fascia?",a:"Soffit is the horizontal panel underneath your roof overhang — it seals the gap between the roofline and the exterior wall. Fascia is the vertical board along the edge of your roofline where gutters attach. Together they protect the edges of your roof structure from water, pests, and weather. When either fails, moisture gets into your attic and roof framing."},
        {q:"Should I choose aluminum or vinyl soffit?",a:"For Florida, we strongly recommend aluminum. It's more durable in extreme heat (vinyl can warp above 120°F — common in direct Florida sun), handles impact better during storms, doesn't fade as quickly, and lasts significantly longer. Vinyl is a budget option that works for some situations, but aluminum is the better long-term investment in our climate."},
        {q:"Do you repair the wood underneath before installing new soffit?",a:"Yes — and this is the most critical step most contractors skip. We pull back the existing soffit and inspect every inch of wood substrate. Rotted, water-damaged, or termite-compromised wood gets replaced before any new material goes on. Wrapping new aluminum over rotten wood is like putting a bandaid on a broken bone — it looks fine but the problem gets worse underneath."},
        {q:"How do I know if my soffit or fascia needs replacing?",a:"Warning signs: paint peeling or bubbling, visible water staining, sagging or warped panels, holes or cracks, soft spots when you push on the material, pest activity near your roofline (wasps, squirrels, birds getting in), detached pieces after storms, or visible daylight from inside your attic. If your home is 15+ years old with original wood soffit, it's worth a free inspection."},
        {q:"How long does soffit and fascia installation take?",a:"Most residential soffit and fascia jobs take 1–3 days depending on the size of your home, the extent of wood repair needed, and accessibility. We give you a timeline before we start. If we discover hidden damage during installation, we'll communicate immediately and adjust — no surprises on the invoice."},
        {q:"What colors and styles are available?",a:"We offer a full range of aluminum soffit colors and styles including solid, vented, and beaded profiles. Fascia wrap is custom-bent on-site to match your exact trim dimensions. Color options include white, almond, brown, black, and custom-matched colors. We bring samples to your consultation so you can see options against your home."},
        {q:"Can you replace just the fascia without replacing the soffit?",a:"Yes. We can replace fascia independently if your soffit is in good condition. However, we always inspect both during our assessment because they work as a system. Replacing fascia while ignoring damaged soffit just moves the failure point. We'll give you an honest recommendation on what actually needs attention."},
        {q:"Does new soffit improve my home's ventilation?",a:"Yes. Vented soffit panels allow air to flow into your attic space, which is critical in Florida. Proper attic ventilation reduces heat buildup (which shortens shingle life), prevents moisture condensation (which causes mold and wood rot), and lowers your cooling costs. If your existing soffit is solid with no vents, upgrading to vented panels is one of the best investments you can make."},
      ]},
      { name:"Peak 301 & Insurance", icon:"⚠️", faqs:[
        {q:"What is Peak 301?",a:"Peak 301 is an all-natural, soy-based roof rejuvenation sealant manufactured by Colorbiotics (a Sika company). It penetrates into your shingle material and restores the oils that UV exposure and heat have depleted over time. It is not a coating, paint, or spray — it works from the inside of the shingle out, restoring flexibility, waterproofing, and structural integrity at the molecular level."},
        {q:"How much does Peak 301 cost compared to roof replacement?",a:"Every roof is different — size, shingle type, and condition all affect the price. For most Tampa Bay homes, Peak 301 treatment runs around 60–75% less than a full replacement ($15,000–$25,000+), and we give you exact pricing only after inspecting your specific roof. The treatment is a one-day application by our crew, warranty documentation, and coordination with an inspector for your Remaining Useful Life (RUL) certification."},
        {q:"Will Peak 301 help me keep my homeowner's insurance?",a:"That's one of its biggest benefits. Florida insurers have increased policy non-renewals by 280% since 2018, primarily targeting roofs over 15 years old. Peak 301 comes with warranty documentation that, combined with a Remaining Useful Life (RUL) certification from an authorized inspector, provides exactly what Florida law (Statute 627.7011) requires carriers to accept for policy renewal."},
        {q:"Is my roof a good candidate for Peak 301?",a:"Most asphalt shingle roofs between 8 and 20 years old are good candidates. Your roof should be structurally sound with no active leaks, no major missing sections, and no severe curling or warping. We inspect every roof honestly before recommending treatment. Not every roof qualifies — and we'd rather tell you the truth than sell a treatment that won't deliver."},
        {q:"Is Peak 301 the same as a roof coating?",a:"No — and this distinction matters. Peak 301 is a penetrating sealant that soaks into your shingles and restores depleted oils from the inside out. Roof coatings create a surface film on top of shingles, which ARMA (the Asphalt Roofing Manufacturers Association) warns against for asphalt shingle roofs. Rejuvenation and coating are two entirely different products."},
        {q:"How long does the treatment last?",a:"Peak 301 adds 6 to 10 years of life to your existing roof, backed by a 6-year warranty guaranteeing a minimum of 6 years added useful life. The exact duration depends on your roof's current condition, age, and shingle type — which we assess before recommending treatment."},
        {q:"What is a Remaining Useful Life (RUL) certification?",a:"An RUL certification is a professional inspection report from a licensed authorized inspector stating that your roof has at least 5 years of remaining useful life. Under Florida Statute 627.7011, insurers cannot refuse to issue or renew your policy solely because of roof age when you provide a valid RUL certification. Peak 301 treatment supports this certification by restoring your shingles to a condition that demonstrates viable remaining life."},
        {q:"What Florida laws protect my roof insurance rights?",a:"Several key laws: Senate Bill 2D (2022) prevents insurers from dropping you solely due to roof age if you have a valid RUL certification. House Bill 1611 (2024) expanded the pool of authorized inspectors to include licensed roofing contractors. Senate Bill 808 and House Bill 815 (both effective July 2026) further expand protections to all property insurance policies and require insurers to base decisions on roof condition, not age. Visit our Insurance Resource Center for the full breakdown."},
        {q:"What should I do if I get a non-renewal notice from my insurer?",a:"Don't panic. Step 1: Request the reason for non-renewal in writing. Step 2: If it's roof age, exercise your right to an inspection under FL Statute 627.7011. Step 3: Get a certified RUL inspection from an authorized inspector. Step 4: Submit the RUL certification with your renewal request. Step 5: If they still refuse, file a complaint with the Florida Office of Insurance Regulation (FLOIR). We walk you through this entire process and provide free document templates at jronegutters.com/insurance-resource-center."},
        {q:"Is Peak 301 safe for my home and landscaping?",a:"Yes. The soy-based formula is non-toxic, biodegradable, and completely safe for your landscaping, pets, and family. No harsh chemicals, no toxic fumes, no environmental concerns. Your landscaping will not be affected by the treatment."},
      ]},
      { name:"Siding & SAGIPER", icon:"🏠", faqs:[
        {q:"What types of siding do you install?",a:"We install vinyl siding, aluminum siding, and SAGIPER premium architectural cladding. Each has different applications — vinyl and aluminum for standard residential siding, SAGIPER for high-end architectural design where aesthetics, durability, and heat performance are critical."},
        {q:"What is SAGIPER and why is it different?",a:"SAGIPER is a premium PVC architectural cladding system from Europe with Solar Shield Technology — the only siding product engineered to handle dark colors in direct Florida sun without warping, fading, or heat damage. Standard vinyl siding is limited to light colors in Florida because dark vinyl absorbs too much heat and distorts. SAGIPER eliminates that limitation while offering modern, design-forward profiles you can't get with standard siding."},
        {q:"Can I use dark-colored siding in Florida?",a:"With standard vinyl siding, no — dark colors absorb too much heat and will warp, buckle, or distort in Florida's sun. With SAGIPER's Solar Shield Technology, yes. SAGIPER is the only product that allows dark exterior cladding in direct Florida sunlight without heat-related failure. This is a major advantage for homeowners and architects who want modern dark exteriors."},
        {q:"How long does siding installation take?",a:"Timeline depends on home size and scope. A standard single-story home typically takes 3–5 days. Larger homes, multi-story work, or projects involving substrate repair may take longer. We provide a specific timeline during your consultation."},
        {q:"Do you repair or replace the wall sheathing underneath?",a:"Yes. Like our soffit work, we inspect the substrate before covering it. If there's moisture damage, rot, or compromised sheathing, we repair it first. Covering bad substrate with new siding creates hidden problems that get worse over time."},
      ]},
      { name:"Warranty & Financing", icon:"📋", faqs:[
        {q:"What warranty do you offer?",a:"We provide a 3-year workmanship warranty from the date of substantial completion. This covers defects in our labor that materially affect system performance under normal residential use. If our work fails because of how we installed it, we come back and fix it at no cost. Product warranties from manufacturers (for gutters, guards, siding, Peak 301, etc.) are separate and vary by product."},
        {q:"Do you offer financing?",a:"Yes. We partner with trusted third-party financing providers so you can protect your home now and pay over time. Quick approval process, flexible terms, and your project pricing stays the same whether you finance or pay in full. Apply through our website or ask about financing during your consultation."},
        {q:"Do I need good credit to qualify for financing?",a:"Our financing partners work with a range of credit profiles. The initial check is typically a soft pull that doesn't affect your credit score. Approval amounts and terms depend on your specific situation. We encourage everyone to apply — you might be surprised."},
        {q:"How do I make a warranty claim?",a:"Call (844) 444-3114 or email info@jronegutters.com. Describe the issue, and we'll schedule an inspection. We don't make warranty claims difficult — we'd rather fix a problem fast than argue about paperwork. If it's our workmanship, we fix it. Period."},
        {q:"Does your warranty cover storm damage?",a:"Our workmanship warranty covers defects in how we installed your system. Storm damage (hurricane, tornado, hail) is covered by your homeowner's insurance, not our warranty. However, if our installation failed in a way that contributed to the damage — for example, hangers that came loose because they were improperly secured — that's on us and we'll make it right."},
        {q:"What's the referral program?",a:"We pay $80 gift cards for qualifying referrals. The referred customer gets 10% off their next service. The qualifying project minimum is $880. All services qualify, and the program is open to everyone — homeowners, insurance agents, roofers, real estate agents, property managers, anyone. No limit on referrals."},
      ]},
      { name:"Maintenance", icon:"🧹", faqs:[
        {q:"How often should I have my gutters cleaned?",a:"In Tampa Bay, at least twice per year — once before hurricane season (May/June) and once after fall leaf drop (November/December). Homes near oak trees, pine trees, or palm trees may need quarterly cleaning. Neglected gutters cause fascia rot, foundation erosion, landscape damage, and pest infestations. Regular cleaning is the cheapest way to prevent expensive repairs."},
        {q:"What's included in your maintenance plans?",a:"We offer three tiers: Basic (blow out gutters, downspouts, and roof line), Premium (everything in Basic plus water wash, flush, full downspout clearing, and miter sealing), and Deluxe (everything in Premium plus full realignment, re-securing of hangers, re-pitching for drainage, and new leaf guard installation). Plans are annual with scheduled visits so you never have to remember to call."},
        {q:"Do you service gutters you didn't install?",a:"Yes. Our maintenance services are available for any gutter system regardless of who installed it. We'll assess the condition of your system during service and let you know if anything needs attention — but there's never pressure to replace or upgrade."},
        {q:"What happens if you find damage during a maintenance visit?",a:"We document everything with photos and communicate immediately. Minor issues (loose hangers, small seal failures) we can often fix on the spot during the service visit. Larger issues (rotted fascia, structural problems, failed sections) we'll provide a separate estimate. You're never obligated — we just want you to know what's going on with your home."},
        {q:"Can I combine gutter cleaning with other services?",a:"Yes. Many homeowners combine gutter cleaning with soffit inspection, guard maintenance, downspout extension checks, and drainage system flushing. Bundling services into one visit saves you time and often costs less than scheduling separately."},
        {q:"Do you offer drainage maintenance?",a:"Yes. If you have French drains, catch basins, underground drainage lines, or pop-up emitters, we can inspect and flush those systems during maintenance visits. Drainage systems accumulate sediment over time and need periodic clearing to maintain flow. A clogged French drain is worse than no drain at all because it traps water against your foundation."},
      ]},
    ],
  },
  es: {
    heroTag: "PREGUNTAS FRECUENTES",
    heroH1a: "Preguntas",
    heroH1b: "Frecuentes",
    heroP: "Todo lo que los propietarios nos preguntan — respondido honestamente. No encuentras tu pregunta? Llama al (844) 444-3114 y te la respondemos directamente.",
    stillTitle: "TODAVIA TIENES PREGUNTAS?",
    stillP: "Preferimos responder tu pregunta directamente a que adivines. Llamanos o escribenos — respondemos rapido.",
    emailBtn: "ENVIANOS UN CORREO",
    categories: [
      { name:"General", icon:"🏠", faqs:[
        {q:"Que servicios ofrece JR One?",a:"Nos especializamos en canaletas de aluminio sin costura (6\" y 7\"), canaletas de cobre, protectores de canaletas (aluminio, estandar, micro malla y EZ mesh), instalacion de sofito y fascia, revestimiento, revestimiento arquitectonico SAGIPER, reparacion de canaletas, rejuvenecimiento de techo Peak 301, instalacion de luces inteligentes Govee, instalacion de drenaje (drenajes franceses, cajas de captacion, canales de drenaje) y planes de mantenimiento completos. Somos especialistas en exteriores de aluminio — es todo lo que hacemos, y lo hacemos bien."},
        {q:"Que areas atienden?",a:"Servimos a 21 ciudades en Tampa Bay y la costa oeste de Florida: Bradenton, Brandon, Clearwater, Dunedin, Lakeland, Land O' Lakes, Largo, Lutz, New Port Richey, Palm Harbor, Plant City, Riverview, Ruskin, Sarasota, Spring Hill, St. Petersburg, Sun City Center, Tampa, Tarpon Springs, Temple Terrace y Wesley Chapel. Si estas a una hora de Tampa, llamanos — probablemente cubrimos tu area."},
        {q:"Usan subcontratistas?",a:"Jamas. Cada persona en tu propiedad es un miembro capacitado y de tiempo completo de la cuadrilla de JR One. Operamos tres cuadrillas internas. Asi es como mantenemos el control de calidad y la responsabilidad en cada trabajo. Muchas de las quejas que los propietarios tienen sobre otros contratistas vienen del trabajo subcontratado — nosotros eliminamos ese problema por completo."},
        {q:"Cuanto tiempo lleva JR One en el negocio?",a:"JR One Aluminum LLC fue formada en 2006 por Christopher Rivera. Las raices familiares en el oficio de canaletas de Tampa Bay se remontan a 1990, cuando el padre de Christopher, Javier Rivera, comenzo a instalar canaletas en Tampa despues de inmigrar de Honduras. Mas de 30 anos de experiencia familiar en la industria de canaletas de Tampa a traves de dos generaciones. Muchas de las empresas de canaletas y sofitos que operan hoy en el mercado de Tampa pueden rastrear su conocimiento hasta Javier — personas que trabajaron para el, con el, o aprendieron a su lado."},
        {q:"Hablan espanol?",a:"Si. JR One es una empresa completamente bilingue — ingles y espanol. Nos comunicamos en el idioma que te resulte mas comodo desde la primera llamada hasta la inspeccion final. Todos nuestros documentos de seguros y recursos estan disponibles en ambos idiomas."},
        {q:"Ofrecen estimados gratis?",a:"Si. Proporcionamos evaluaciones gratuitas en sitio para todos los servicios. Inspeccionaremos tu hogar, discutiremos tus necesidades y proporcionaremos un estimado detallado y transparente sin obligacion y sin presion. Tambien puedes usar nuestra herramienta de Estimador Aereo en linea para medir tu techo desde imagenes satelitales y obtener un rango de precios instantaneo antes de que visitemos."},
        {q:"Que hace diferente a JR One de otros contratistas?",a:"Tres cosas: (1) Solo hacemos exteriores de aluminio — canaletas, sofito, fascia, revestimiento, protectores, drenaje. Sin techado, sin pintura, sin contratacion general. Esto significa que nuestras cuadrillas son especialistas, no generalistas. (2) Todas las cuadrillas son internas — sin subcontratistas, jamas. (3) Empresa familiar, operada por la familia, con mas de 30 anos de experiencia en la industria de canaletas de Tampa Bay a traves de dos generaciones. Hemos instalado en algunas de las mismas casas dos veces."},
        {q:"Que es el proceso del Estandar de Oro?",a:"Cada proyecto de JR One sigue cuatro pasos: Evaluar (inspeccionar tu hogar e identificar el problema real), Disenar (solucion personalizada con precios transparentes), Instalar (nuestra cuadrilla capacitada hace el trabajo — sin atajos) y Proteger (inspeccion final, documentacion y garantia). Este proceso aplica a cada servicio, cada hogar, sin excepciones."},
        {q:"Estan licenciados y asegurados?",a:"Si. JR One Aluminum LLC esta completamente licenciada y asegurada en el estado de Florida. Tenemos seguro de responsabilidad general y cobertura de compensacion para trabajadores. Con gusto proporcionamos prueba de seguro a cualquier propietario o administrador de propiedades que lo solicite."},
      ]},
      { name:"Canaletas", icon:"💧", faqs:[
        {q:"Que tamanos de canaletas instalan?",a:"Instalamos canaletas de aluminio sin costura de 6\" y 7\". Las de 6\" manejan la mayoria de las aplicaciones residenciales con excelente capacidad de agua. Las de 7\" son nuestra opcion de alta capacidad para areas de techo mas grandes, pendientes mas pronunciadas y edificios comerciales. Evaluamos tu techo y recomendamos el tamano correcto — no usamos canaletas mas pequenas para ahorrar unos dolares."},
        {q:"Cuanto cuestan las canaletas nuevas en Tampa?",a:"La instalacion de canaletas de aluminio sin costura en Tampa varia segun el tamano de la canaleta (6\" o 7\"), pies lineales, accesibilidad, numero de esquinas, configuracion de bajantes y pisos. Proporcionamos estimados detallados con cada item desglosado para que veas exactamente lo que estas pagando. Usa nuestro Estimador Aereo en jronegutters.com/estimator para un rango de precios instantaneo."},
        {q:"Que son las canaletas sin costura y por que importan?",a:"Las canaletas sin costura se fabrican en sitio a partir de una sola pieza continua de aluminio — sin costuras, sin juntas, sin puntos de empalme a lo largo del recorrido. Las canaletas seccionales tradicionales tienen juntas cada 10 pies que eventualmente gotean. Las canaletas sin costura eliminan esos puntos de falla, lo que significa menos fugas, menos mantenimiento y una apariencia mas limpia en tu hogar."},
        {q:"Cuanto duran las canaletas sin costura?",a:"Con mantenimiento adecuado, las canaletas de aluminio sin costura de calidad duran 20–30 anos en el clima de Florida. El aluminio en si no se oxida ni se pudre. Lo que acorta la vida de las canaletas es el descuido — bajantes tapados, agua estancada y acumulacion de escombros que causa corrosion. Por eso recomendamos planes de mantenimiento y protectores de canaletas."},
        {q:"Cuanto tiempo toma la instalacion de canaletas?",a:"La mayoria de las instalaciones residenciales de canaletas se completan en un solo dia. Hogares con lineas de techo complejas, multiples pisos o proyectos combinados (canaletas + sofito/fascia + protectores) pueden tomar 2–3 dias. Te damos un cronograma antes de empezar y lo cumplimos."},
        {q:"Que opciones de bajantes ofrecen?",a:"Instalamos bajantes rectangulares estandar, rectangulares lisos, redondos (dos tamanos), comerciales 4x5, comerciales tipo caja y cadenas de lluvia decorativas. El tamano y ubicacion de los bajantes se calculan segun el tamano de tu canaleta y los pies cuadrados de tu techo para asegurar el manejo adecuado del agua — no solo la estetica."},
        {q:"Ofrecen canaletas de cobre?",a:"Si. Instalamos sistemas premium de canaletas de cobre de media cana y estilo K con bajantes de cobre, cabezales y cadenas de lluvia a juego. El cobre desarrolla una patina natural con el tiempo y dura mas de 50 anos con cero mantenimiento. Es una inversion de por vida para propietarios que quieren lo mejor."},
        {q:"Por que deberia contratar un especialista en canaletas en vez de mi techador?",a:"Las empresas de techado tipicamente subcontratan el trabajo de canaletas al postor mas bajo. El resultado a menudo es una inclinacion incorrecta, material de calibre delgado y trabajo de esquinas deficiente que lleva a fugas en pocos anos. Nosotros nos especializamos exclusivamente en sistemas de aluminio — es todo lo que hacemos. Cada instalacion es realizada por nuestra cuadrilla interna capacitada usando materiales de grado comercial."},
        {q:"Mis canaletas se desbordan durante lluvias fuertes. Que esta mal?",a:"Tres causas comunes: (1) Las canaletas estan tapadas con escombros — necesitan limpieza. (2) Las canaletas son muy pequenas para el area de tu techo — comun cuando los constructores instalan canaletas subdimensionadas en hogares que necesitan 6\" o 7\". (3) Las canaletas tienen inclinacion incorrecta — el agua se acumula en vez de fluir hacia los bajantes. Diagnosticamos la causa exacta durante una inspeccion gratuita."},
        {q:"Hacen reparacion de canaletas o solo reemplazo completo?",a:"Ambos. Reparamos secciones que se hunden, arreglamos costuras y esquinas con fugas, reemplazamos bajantes danados, re-inclinamos canaletas para drenaje adecuado y re-aseguramos ganchos. Si la reparacion tiene sentido, te lo diremos. Si tu sistema esta mas alla de la reparacion, seremos honestos al respecto."},
      ]},
      { name:"Protectores de Canaletas", icon:"🛡️", faqs:[
        {q:"Realmente funcionan los protectores de canaletas?",a:"Si — los protectores son altamente efectivos para mantener los escombros fuera de tus canaletas y prevenir obstrucciones en bajantes y drenaje. No eliminan todo el mantenimiento, pero reducen dramaticamente la frecuencia de limpieza de 2–4 veces al ano a una vez al ano o menos. El valor real es prevenir el dano que causan las canaletas tapadas: erosion de cimientos, pudricion de fascia, dano al paisajismo y problemas de plagas."},
        {q:"Que tipos de protectores de canaletas instalan?",a:"Instalamos cuatro tipos: Protectores de aluminio (solidos con canales de agua — ideales para escombros pesados), Protectores de malla estandar (proteccion general economica), Protectores de micro malla (filtracion mas fina — bloquean agujas de pino, gránulos de tejas y semillas pequenas) y Protectores EZ Mesh (opcion de facil mantenimiento con excelente flujo de aire). Recomendamos el tipo correcto segun tu cobertura de arboles y tipo de escombros."},
        {q:"Todavia necesito limpiar mis canaletas despues de instalar protectores?",a:"Si, pero mucho menos seguido. Los protectores evitan que los escombros entren dentro de tus canaletas — ahi es donde ocurre el dano real. La acumulacion superficial encima de los protectores aun necesita limpieza ocasional, tipicamente una vez al ano. Compara eso con limpiar canaletas sin proteccion 2–4 veces al ano. Ofrecemos programas de mantenimiento para encargarnos de esto por ti."},
        {q:"Cual es el mejor protector de canaletas para agujas de pino?",a:"Los protectores de micro malla son la opcion mas efectiva para agujas de pino. Los protectores de malla estandar tienen aberturas lo suficientemente grandes para que las agujas pasen y se acumulen adentro. La micro malla bloquea todo hasta granulos de tejas mientras permite el flujo completo de agua. Si tienes pinos, robles o palmeras, la micro malla es lo que recomendamos."},
        {q:"Se pueden instalar protectores en mis canaletas existentes?",a:"Si. Instalamos protectores en sistemas de canaletas existentes — no necesitas canaletas nuevas para obtener proteccion. Inspeccionamos tus canaletas existentes primero para asegurarnos de que esten en buena condicion, correctamente inclinadas y bien aseguradas. Si se necesitan reparaciones, las manejamos antes de instalar los protectores."},
        {q:"Cual es la diferencia entre sus protectores y LeafFilter u otras marcas nacionales?",a:"Las empresas nacionales como LeafFilter usan ventas de alta presion, cobran precios premium (a menudo 2–3 veces las tarifas locales) y subcontratan la instalacion a quien este disponible. Nosotros somos el equipo local — tratas directamente con nosotros, obtienes precios honestos sin margen de franquicia, y nuestra propia cuadrilla hace tanto la consulta como la instalacion. Sin vendedores en tu sala por dos horas."},
        {q:"Los protectores de canaletas anulan la garantia de mis canaletas?",a:"No. Nuestras instalaciones de protectores estan disenadas para funcionar con tu sistema de canaletas existente sin modificar ni danar las canaletas. Si nosotros instalamos tus canaletas, la garantia de mano de obra permanece completamente intacta."},
        {q:"Cuanto duran los protectores de canaletas?",a:"Los protectores de aluminio y micro malla duran 15–20+ anos. Estan expuestos al mismo clima que tus canaletas pero no cargan peso de agua ni acumulacion de escombros, asi que tipicamente duran mas que las canaletas mismas. Usamos materiales de grado comercial — no las cosas delgadas que encuentras en las tiendas de mejoras para el hogar."},
      ]},
      { name:"Sofito y Fascia", icon:"🏗️", faqs:[
        {q:"Cual es la diferencia entre sofito y fascia?",a:"El sofito es el panel horizontal debajo del voladizo de tu techo — sella el espacio entre la linea del techo y la pared exterior. La fascia es la tabla vertical a lo largo del borde de tu linea de techo donde se fijan las canaletas. Juntos protegen los bordes de la estructura de tu techo contra agua, plagas y clima. Cuando cualquiera falla, la humedad entra en tu atico y la estructura del techo."},
        {q:"Deberia elegir sofito de aluminio o vinilo?",a:"Para Florida, recomendamos firmemente el aluminio. Es mas duradero en calor extremo (el vinilo puede deformarse por encima de 120°F — comun bajo el sol directo de Florida), resiste mejor los impactos durante tormentas, no se descolora tan rapido y dura significativamente mas. El vinilo es una opcion economica que funciona para algunas situaciones, pero el aluminio es la mejor inversion a largo plazo en nuestro clima."},
        {q:"Reparan la madera debajo antes de instalar sofito nuevo?",a:"Si — y este es el paso mas critico que la mayoria de los contratistas se saltan. Retiramos el sofito existente e inspeccionamos cada centimetro del sustrato de madera. La madera podrida, danada por agua o comprometida por termitas se reemplaza antes de que se ponga cualquier material nuevo. Cubrir madera podrida con aluminio nuevo es como poner una curita en un hueso roto — se ve bien pero el problema empeora por debajo."},
        {q:"Como se si mi sofito o fascia necesita reemplazo?",a:"Senales de alerta: pintura descascarandose o burbujeandose, manchas de agua visibles, paneles hundidos o deformados, agujeros o grietas, puntos blandos cuando presionas el material, actividad de plagas cerca de la linea del techo (avispas, ardillas, pajaros entran), piezas desprendidas despues de tormentas, o luz del dia visible desde dentro del atico. Si tu hogar tiene 15+ anos con sofito original de madera, vale la pena una inspeccion gratuita."},
        {q:"Cuanto tiempo toma la instalacion de sofito y fascia?",a:"La mayoria de los trabajos residenciales de sofito y fascia toman 1–3 dias dependiendo del tamano de tu hogar, la extension de la reparacion de madera necesaria y la accesibilidad. Te damos un cronograma antes de empezar. Si descubrimos danos ocultos durante la instalacion, nos comunicamos inmediatamente y ajustamos — sin sorpresas en la factura."},
        {q:"Que colores y estilos estan disponibles?",a:"Ofrecemos una gama completa de colores y estilos de sofito de aluminio incluyendo perfiles solidos, ventilados y con moldura. La envoltura de fascia se dobla a medida en sitio para coincidir con las dimensiones exactas de tu moldura. Las opciones de color incluyen blanco, almendra, marron, negro y colores personalizados. Llevamos muestras a tu consulta para que puedas ver las opciones contra tu hogar."},
        {q:"Pueden reemplazar solo la fascia sin reemplazar el sofito?",a:"Si. Podemos reemplazar la fascia independientemente si tu sofito esta en buena condicion. Sin embargo, siempre inspeccionamos ambos durante nuestra evaluacion porque funcionan como un sistema. Reemplazar la fascia mientras se ignora el sofito danado solo mueve el punto de falla. Te daremos una recomendacion honesta sobre lo que realmente necesita atencion."},
        {q:"El sofito nuevo mejora la ventilacion de mi hogar?",a:"Si. Los paneles de sofito ventilado permiten que el aire fluya hacia el espacio del atico, lo cual es critico en Florida. La ventilacion adecuada del atico reduce la acumulacion de calor (que acorta la vida de las tejas), previene la condensacion de humedad (que causa moho y pudricion de madera) y reduce tus costos de enfriamiento. Si tu sofito existente es solido sin ventilaciones, actualizar a paneles ventilados es una de las mejores inversiones que puedes hacer."},
      ]},
      { name:"Peak 301 y Seguros", icon:"⚠️", faqs:[
        {q:"Que es Peak 301?",a:"Peak 301 es un sellador de rejuvenecimiento de techo totalmente natural a base de soya fabricado por Colorbiotics (una empresa de Sika). Penetra en el material de tus tejas y restaura los aceites que la exposicion UV y el calor han agotado con el tiempo. No es un recubrimiento, pintura ni spray — trabaja desde el interior de la teja hacia afuera, restaurando flexibilidad, impermeabilizacion e integridad estructural a nivel molecular."},
        {q:"Cuanto cuesta Peak 301 comparado con el reemplazo del techo?",a:"Cada techo es diferente — tamano, tipo de teja y condicion afectan el precio. Para la mayoria de los hogares de Tampa Bay, el tratamiento Peak 301 cuesta alrededor de 60–75% menos que un reemplazo completo ($15,000–$25,000+), y le damos precios exactos solo despues de inspeccionar su techo especifico. El tratamiento es una aplicacion de un solo dia por nuestra cuadrilla, documentacion de garantia y coordinacion con un inspector para tu certificacion de Vida Util Remanente (RUL)."},
        {q:"Peak 301 me ayudara a mantener mi seguro de hogar?",a:"Ese es uno de sus mayores beneficios. Las aseguradoras de Florida han aumentado las no-renovaciones de polizas en un 280% desde 2018, apuntando principalmente a techos de mas de 15 anos. Peak 301 viene con documentacion de garantia que, combinada con una certificacion de Vida Util Remanente (RUL) de un inspector autorizado, proporciona exactamente lo que la ley de Florida (Estatuto 627.7011) requiere que las aseguradoras acepten para la renovacion de polizas."},
        {q:"Mi techo es buen candidato para Peak 301?",a:"La mayoria de los techos de tejas asfalticas entre 8 y 20 anos son buenos candidatos. Tu techo debe estar estructuralmente solido sin fugas activas, sin secciones faltantes importantes y sin enrollamiento o deformacion severa. Inspeccionamos cada techo honestamente antes de recomendar el tratamiento. No todos los techos califican — y preferimos decirte la verdad que vender un tratamiento que no dara resultados."},
        {q:"Peak 301 es lo mismo que un recubrimiento de techo?",a:"No — y esta distincion importa. Peak 301 es un sellador penetrante que se absorbe en tus tejas y restaura los aceites agotados desde adentro hacia afuera. Los recubrimientos de techo crean una pelicula superficial encima de las tejas, contra lo cual ARMA (la Asociacion de Fabricantes de Techos Asfalticos) advierte para techos de tejas asfalticas. Rejuvenecimiento y recubrimiento son dos productos completamente diferentes."},
        {q:"Cuanto dura el tratamiento?",a:"Peak 301 agrega 6 a 10 anos de vida a tu techo existente, respaldado por una garantia de 6 anos que asegura un minimo de 6 anos de vida util adicional. La duracion exacta depende de la condicion actual de tu techo, su edad y tipo de teja — lo cual evaluamos antes de recomendar el tratamiento."},
        {q:"Que es una certificacion de Vida Util Remanente (RUL)?",a:"Una certificacion RUL es un informe de inspeccion profesional de un inspector autorizado licenciado que declara que tu techo tiene al menos 5 anos de vida util remanente. Bajo el Estatuto de Florida 627.7011, las aseguradoras no pueden negarse a emitir o renovar tu poliza unicamente por la edad del techo cuando proporcionas una certificacion RUL valida. El tratamiento Peak 301 respalda esta certificacion al restaurar tus tejas a una condicion que demuestra vida util viable."},
        {q:"Que leyes de Florida protegen mis derechos de seguro de techo?",a:"Varias leyes clave: El Proyecto de Ley del Senado 2D (2022) previene que las aseguradoras te cancelen unicamente por la edad del techo si tienes una certificacion RUL valida. El Proyecto de Ley de la Camara 1611 (2024) amplio el grupo de inspectores autorizados para incluir contratistas de techado licenciados. El Proyecto de Ley del Senado 808 y el Proyecto de Ley de la Camara 815 (ambos efectivos en julio 2026) amplian aun mas las protecciones a todas las polizas de seguro de propiedad y requieren que las aseguradoras basen sus decisiones en la condicion del techo, no en su edad. Visita nuestro Centro de Recursos de Seguros para el desglose completo."},
        {q:"Que debo hacer si recibo un aviso de no-renovacion de mi aseguradora?",a:"No entres en panico. Paso 1: Solicita la razon de la no-renovacion por escrito. Paso 2: Si es por la edad del techo, ejerce tu derecho a una inspeccion bajo el Estatuto de Florida 627.7011. Paso 3: Obtene una inspeccion RUL certificada de un inspector autorizado. Paso 4: Presenta la certificacion RUL con tu solicitud de renovacion. Paso 5: Si aun se niegan, presenta una queja ante la Oficina de Regulacion de Seguros de Florida (FLOIR). Te guiamos por todo este proceso y proporcionamos plantillas de documentos gratuitas en jronegutters.com/insurance-resource-center."},
        {q:"Peak 301 es seguro para mi hogar y jardines?",a:"Si. La formula a base de soya es no toxica, biodegradable y completamente segura para tu jardin, mascotas y familia. Sin quimicos agresivos, sin humos toxicos, sin preocupaciones ambientales. Tu jardin no se vera afectado por el tratamiento."},
      ]},
      { name:"Revestimiento y SAGIPER", icon:"🏠", faqs:[
        {q:"Que tipos de revestimiento instalan?",a:"Instalamos revestimiento de vinilo, revestimiento de aluminio y revestimiento arquitectonico premium SAGIPER. Cada uno tiene diferentes aplicaciones — vinilo y aluminio para revestimiento residencial estandar, SAGIPER para diseno arquitectonico de alta gama donde la estetica, durabilidad y rendimiento termico son criticos."},
        {q:"Que es SAGIPER y por que es diferente?",a:"SAGIPER es un sistema de revestimiento arquitectonico premium de PVC de Europa con tecnologia Solar Shield — el unico producto de revestimiento disenado para manejar colores oscuros bajo el sol directo de Florida sin deformarse, decolorarse o sufrir danos por calor. El revestimiento de vinilo estandar esta limitado a colores claros en Florida porque el vinilo oscuro absorbe demasiado calor y se distorsiona. SAGIPER elimina esa limitacion mientras ofrece perfiles modernos y de diseno avanzado que no puedes obtener con revestimiento estandar."},
        {q:"Puedo usar revestimiento de color oscuro en Florida?",a:"Con revestimiento de vinilo estandar, no — los colores oscuros absorben demasiado calor y se deformaran, pandean o distorsionan bajo el sol de Florida. Con la tecnologia Solar Shield de SAGIPER, si. SAGIPER es el unico producto que permite revestimiento exterior oscuro bajo la luz solar directa de Florida sin fallas relacionadas con el calor. Esta es una gran ventaja para propietarios y arquitectos que desean exteriores oscuros modernos."},
        {q:"Cuanto tiempo toma la instalacion de revestimiento?",a:"El cronograma depende del tamano de la casa y el alcance. Una casa estandar de un piso tipicamente toma 3–5 dias. Casas mas grandes, trabajo de varios pisos o proyectos que involucran reparacion de sustrato pueden tomar mas tiempo. Proporcionamos un cronograma especifico durante tu consulta."},
        {q:"Reparan o reemplazan el revestimiento de pared debajo?",a:"Si. Al igual que nuestro trabajo de sofito, inspeccionamos el sustrato antes de cubrirlo. Si hay dano por humedad, pudricion o revestimiento comprometido, lo reparamos primero. Cubrir un mal sustrato con revestimiento nuevo crea problemas ocultos que empeoran con el tiempo."},
      ]},
      { name:"Garantia y Financiamiento", icon:"📋", faqs:[
        {q:"Que garantia ofrecen?",a:"Proporcionamos una garantia de mano de obra de 3 anos desde la fecha de finalizacion sustancial. Esto cubre defectos en nuestra mano de obra que afectan materialmente el rendimiento del sistema bajo uso residencial normal. Si nuestro trabajo falla por como lo instalamos, regresamos y lo arreglamos sin costo. Las garantias de productos de los fabricantes (para canaletas, protectores, revestimiento, Peak 301, etc.) son separadas y varian segun el producto."},
        {q:"Ofrecen financiamiento?",a:"Si. Nos asociamos con proveedores de financiamiento terceros de confianza para que puedas proteger tu hogar ahora y pagar con el tiempo. Proceso de aprobacion rapido, terminos flexibles, y el precio de tu proyecto se mantiene igual ya sea que financies o pagues por completo. Aplica a traves de nuestro sitio web o pregunta sobre el financiamiento durante tu consulta."},
        {q:"Necesito buen credito para calificar para financiamiento?",a:"Nuestros socios de financiamiento trabajan con una variedad de perfiles crediticios. La verificacion inicial es tipicamente una consulta suave que no afecta tu puntaje de credito. Los montos de aprobacion y terminos dependen de tu situacion especifica. Animamos a todos a aplicar — podrias sorprenderte."},
        {q:"Como hago un reclamo de garantia?",a:"Llama al (844) 444-3114 o envia un correo a info@jronegutters.com. Describe el problema y programaremos una inspeccion. No hacemos dificiles los reclamos de garantia — preferimos arreglar un problema rapido que discutir sobre papeles. Si es nuestra mano de obra, lo arreglamos. Punto."},
        {q:"Su garantia cubre danos por tormentas?",a:"Nuestra garantia de mano de obra cubre defectos en como instalamos tu sistema. Los danos por tormentas (huracan, tornado, granizo) estan cubiertos por tu seguro de hogar, no nuestra garantia. Sin embargo, si nuestra instalacion fallo de una manera que contribuyo al dano — por ejemplo, ganchos que se soltaron porque estaban mal asegurados — eso es nuestra responsabilidad y lo resolveremos."},
        {q:"Cual es el programa de referidos?",a:"Pagamos tarjetas de regalo de $80 por referidos que califiquen. El cliente referido obtiene 10% de descuento en su proximo servicio. El minimo de proyecto para calificar es $880. Todos los servicios califican, y el programa esta abierto para todos — propietarios, agentes de seguros, techadores, agentes de bienes raices, administradores de propiedades, cualquiera. Sin limite de referidos."},
      ]},
      { name:"Mantenimiento", icon:"🧹", faqs:[
        {q:"Con que frecuencia debo limpiar mis canaletas?",a:"En Tampa Bay, al menos dos veces al ano — una antes de la temporada de huracanes (mayo/junio) y una despues de la caida de hojas de otono (noviembre/diciembre). Hogares cerca de robles, pinos o palmeras pueden necesitar limpieza trimestral. Las canaletas descuidadas causan pudricion de fascia, erosion de cimientos, dano al paisajismo e infestaciones de plagas. La limpieza regular es la forma mas barata de prevenir reparaciones costosas."},
        {q:"Que incluyen sus planes de mantenimiento?",a:"Ofrecemos tres niveles: Basico (soplado de canaletas, bajantes y linea de techo), Premium (todo en Basico mas lavado con agua, enjuague, limpieza completa de bajantes y sellado de ingletetes) y Deluxe (todo en Premium mas realineacion completa, re-aseguramiento de ganchos, re-inclinacion para drenaje e instalacion de protectores nuevos). Los planes son anuales con visitas programadas para que nunca tengas que acordarte de llamar."},
        {q:"Dan servicio a canaletas que no instalaron?",a:"Si. Nuestros servicios de mantenimiento estan disponibles para cualquier sistema de canaletas sin importar quien lo instalo. Evaluaremos la condicion de tu sistema durante el servicio y te haremos saber si algo necesita atencion — pero nunca hay presion para reemplazar o mejorar."},
        {q:"Que pasa si encuentran danos durante una visita de mantenimiento?",a:"Documentamos todo con fotos y nos comunicamos inmediatamente. Problemas menores (ganchos sueltos, pequenas fallas de sellado) a menudo podemos arreglarlos en el momento durante la visita de servicio. Problemas mayores (fascia podrida, problemas estructurales, secciones fallidas) proporcionaremos un estimado separado. Nunca estas obligado — solo queremos que sepas lo que esta pasando con tu hogar."},
        {q:"Puedo combinar limpieza de canaletas con otros servicios?",a:"Si. Muchos propietarios combinan la limpieza de canaletas con inspeccion de sofito, mantenimiento de protectores, verificacion de extensiones de bajantes y lavado de sistemas de drenaje. Combinar servicios en una visita te ahorra tiempo y a menudo cuesta menos que programar por separado."},
        {q:"Ofrecen mantenimiento de drenaje?",a:"Si. Si tienes drenajes franceses, cajas de captacion, lineas de drenaje subterraneas o emisores emergentes, podemos inspeccionar y lavar esos sistemas durante las visitas de mantenimiento. Los sistemas de drenaje acumulan sedimento con el tiempo y necesitan limpieza periodica para mantener el flujo. Un drenaje frances tapado es peor que no tener drenaje porque atrapa el agua contra tus cimientos."},
      ]},
    ],
  },
};

export default function FAQPage() {
  const [activeCategory, setActiveCategory] = useState(0);
  const [openFaq, setOpenFaq] = useState(null);
  const { lang } = useLanguage();
  const t = T[lang];
  useEffect(() => { injectFonts(); }, []);
  const secTitle = {fontFamily:f.h,fontSize:"clamp(24px,4vw,36px)",fontWeight:800,letterSpacing:"2px",textAlign:"center",marginBottom:"8px"};
  const activeCat = t.categories[activeCategory];

  return (
    <div style={{background:C.bg,color:C.white,fontFamily:f.b,lineHeight:1.65,minHeight:"100vh"}}>
      <SiteNav />

      <section className="hero-stars" style={{padding:"60px 24px 20px",maxWidth:"900px",margin:"0 auto",textAlign:"center"}}>
        <Tag>{t.heroTag}</Tag>
        <h1 style={{fontFamily:f.h,fontSize:"clamp(32px,5vw,44px)",fontWeight:800,lineHeight:1.1,marginBottom:"16px"}}>{t.heroH1a}<br/><span style={{color:C.gold}}>{t.heroH1b}</span></h1>
        <p style={{fontFamily:f.b,fontSize:"18px",color:C.muted,maxWidth:"600px",margin:"0 auto"}}>{t.heroP}</p>
      </section>

      {/* CATEGORY TABS */}
      <section style={{padding:"20px 24px 0"}}>
        <div style={{maxWidth:"900px",margin:"0 auto",display:"flex",flexWrap:"wrap",justifyContent:"center",gap:"8px"}}>
          {t.categories.map((cat,i) => (
            <button key={i} onClick={()=>{setActiveCategory(i);setOpenFaq(null);}} style={{
              padding:"10px 18px",fontFamily:f.h,fontSize:"13px",fontWeight:600,
              background:activeCategory===i?C.gold:C.navyFade,
              color:activeCategory===i?C.navy:C.muted,
              border:`1px solid ${activeCategory===i?C.gold:C.navyLight}`,
              borderRadius:"8px",cursor:"pointer",transition:"all 0.2s"
            }}>{cat.icon} {cat.name}</button>
          ))}
        </div>
      </section>

      {/* FAQ LIST */}
      <section style={{padding:"40px 24px 80px"}}>
        <div style={{maxWidth:"800px",margin:"0 auto"}}>
          <h2 style={{fontFamily:f.h,fontSize:"20px",fontWeight:700,color:C.gold,marginBottom:"24px"}}>{activeCat?.icon} {activeCat?.name}</h2>
          {activeCat?.faqs.map((faq,i) => (
            <div key={i} style={{borderBottom:`1px solid ${C.navyLight}`}}>
              <button onClick={()=>setOpenFaq(openFaq===i?null:i)} style={{width:"100%",padding:"20px 0",background:"none",border:"none",cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center",gap:"16px"}}>
                <span style={{fontFamily:f.h,fontSize:"15px",fontWeight:600,color:openFaq===i?C.gold:C.white,textAlign:"left",transition:"color 0.2s"}}>{faq.q}</span>
                <span style={{fontFamily:f.h,fontSize:"20px",color:C.gold,transform:openFaq===i?"rotate(45deg)":"none",transition:"transform 0.3s",flexShrink:0}}>+</span>
              </button>
              {openFaq===i && <div style={{padding:"0 0 20px",fontFamily:f.b,fontSize:"15px",color:C.muted,lineHeight:1.65}}>{faq.a}</div>}
            </div>
          ))}
        </div>
      </section>

      {/* STILL HAVE QUESTIONS */}
      <section style={{background:C.navy,padding:"60px 24px",textAlign:"center"}}>
        <h2 style={{fontFamily:f.h,fontSize:"28px",fontWeight:800,color:C.white,marginBottom:"12px"}}>{t.stillTitle}</h2>
        <p style={{fontFamily:f.b,fontSize:"16px",color:C.offWhite,marginBottom:"24px",maxWidth:"500px",margin:"0 auto 24px"}}>{t.stillP}</p>
        <div style={{display:"flex",gap:"16px",justifyContent:"center",flexWrap:"wrap"}}>
          <a href="tel:8444443114" style={{display:"inline-flex",alignItems:"center",gap:"8px",padding:"16px 32px",fontFamily:f.h,fontSize:"14px",fontWeight:700,letterSpacing:"1.5px",color:C.navy,background:`linear-gradient(135deg,${C.gold},${C.goldLight})`,borderRadius:"8px",textDecoration:"none"}}>📞 (844) 444-3114</a>
          <a href="mailto:info@jronegutters.com" style={{padding:"16px 32px",fontFamily:f.h,fontSize:"14px",fontWeight:700,letterSpacing:"1.5px",color:C.gold,border:`2px solid ${C.gold}`,borderRadius:"8px",textDecoration:"none"}}>{t.emailBtn}</a>
        </div>
      </section>

      <SiteFooter />
      <MobileCTA />
      <style>{`*{box-sizing:border-box;margin:0;padding:0}`}</style>
    </div>
  );
}
